# Generated by Django 6.0 on 2025-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
