# Generated by Django 6.0 on 2025-12-19 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_poll_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_option',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telegram_id',
            new_name='tg_id',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='role',
            field=models.CharField(choices=[('parent', 'Для родителей'), ('student', 'Для учеников')], default='parent', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('parent', 'Родитель'), ('student', 'Ученик')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(),
        ),
    ]
