# Generated by Django 6.0 on 2025-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_selected_option_answer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='telegram_poll_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
