# Generated by Django 6.0 on 2025-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_telegram_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Опрос с вариантами'), ('scale_group', 'Группа утверждений (шкала)'), ('text', 'Открытый вопрос')], default='choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='options',
            field=models.JSONField(blank=True, help_text='Для choice: список вариантов ответа.\nДля scale_group: список утверждений.\nДля text: оставить пустым.', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(help_text='Основной текст вопроса или вводный текст'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='role',
            field=models.CharField(choices=[('parent', 'Родитель'), ('student', 'Ученик')], max_length=10),
        ),
        migrations.AlterField(
            model_name='poll',
            name='telegram_poll_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
