# Generated by Django 6.0 on 2025-12-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор (получает AI-отчёты)'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Опрос с вариантами (1 ответ)'), ('multi_choice', 'Опрос с несколькими вариантами'), ('scale_group', 'Группа утверждений (шкала)'), ('text', 'Открытый вопрос')], default='choice', max_length=20),
        ),
    ]
